# lrsomatic_report packaged as a container, so consumers (the LRSomatic Nextflow pipeline)
# can pull the tool instead of vendoring a copy of this source tree.
#
# The install layout below is the one recipe/build.sh produces, so once `lrsomatic-report`
# reaches bioconda the biocontainer is a drop-in replacement and callers change nothing but
# the image reference.
#
# Built by .github/workflows/container.yml on a v* tag and published as
#   ghcr.io/ljwharbers/lrsomatic-report:<version>            (OCI)
#   oras://ghcr.io/ljwharbers/lrsomatic-report-sif:<version> (Apptainer SIF)
FROM condaforge/miniforge3:26.7.2-0

ARG VERSION=dev
LABEL org.opencontainers.image.title="lrsomatic_report" \
      org.opencontainers.image.description="R/Quarto reporting tool for the LRSomatic long-read somatic variant calling pipeline" \
      org.opencontainers.image.source="https://github.com/ljwharbers/lrsomatic_report" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.licenses="MIT"

SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

# procps-ng: Nextflow's task monitor calls `ps` inside the container. It is not a dependency
# of the tool, which is why it is here and not in recipe/meta.yaml.
COPY container/environment.yml /tmp/environment.yml
RUN mamba env update -n base -f /tmp/environment.yml \
 && mamba install -y -n base conda-forge::procps-ng \
 && mamba clean -afy \
 && rm -f /tmp/environment.yml

# CONDA_PREFIX: activate.d holds a hook from every package that ships one, not just quarto's,
# and some of them (activate-gcc_linux-64.sh, from the compiler runtime r-base pulls in)
# dereference CONDA_PREFIX and fail when it is unset. There is exactly one environment here.
ENV PATH=/opt/conda/bin:$PATH \
    CONDA_PREFIX=/opt/conda \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

# Same layout as recipe/build.sh, so a future biocontainer is a drop-in replacement.
# render_report.R takes dirname($0)/.. as its repo_dir, which lands on share/lrsomatic_report.
COPY bin/       /opt/conda/share/lrsomatic_report/bin/
COPY R/         /opt/conda/share/lrsomatic_report/R/
COPY templates/ /opt/conda/share/lrsomatic_report/templates/
COPY assets/    /opt/conda/share/lrsomatic_report/assets/
COPY VERSION LICENSE /opt/conda/share/lrsomatic_report/

# recipe/build.sh symlinks bin/render_report.R onto PATH, which is right for the conda
# package because activating the environment runs etc/conda/activate.d/*.sh. Nothing does
# that here: `apptainer exec` and a Nextflow task both invoke the binary directly. quarto's
# conda package needs eight variables from that hook -- QUARTO_DENO, QUARTO_PANDOC,
# QUARTO_DENO_DOM, QUARTO_ESBUILD, QUARTO_TYPST, QUARTO_DART_SASS, QUARTO_SHARE_PATH and
# QUARTO_CONDA_PREFIX -- and some of their values are generated at package build time, so
# they cannot be written as static ENV. A wrapper sources the hook instead, which keeps the
# activation dance inside the image where it belongs rather than in every caller's script.
# render_report.R still resolves its own repo_dir from $0, so the wrapper passes the real
# path and the layout stays identical to the conda package's.
RUN chmod +x /opt/conda/share/lrsomatic_report/bin/render_report.R \
 && printf '%s\n' \
      '#!/bin/bash' \
      '# Generated by the Dockerfile -- see the comment there. The conda package uses a' \
      '# plain symlink, because `conda activate` runs these hooks for you.' \
      'for hook in /opt/conda/etc/conda/activate.d/*.sh; do' \
      '    [ -f "$hook" ] && . "$hook"' \
      'done' \
      'exec Rscript /opt/conda/share/lrsomatic_report/bin/render_report.R "$@"' \
    > /opt/conda/bin/render_report.R \
 && chmod +x /opt/conda/bin/render_report.R \
 && chmod -R a+rX /opt/conda/share/lrsomatic_report

# Build-time assertions. Each stands for a way this image has a plausible path to being
# silently broken: an activation hook that stopped exporting something quarto needs, a
# missing R dependency that would only show up mid-render, and a wrapper whose repo_dir
# does not resolve.
# set +u because SHELL turns it on for every RUN, and these hooks are third-party scripts:
# we cannot promise what else they dereference. -e stays on, from SHELL.
RUN set +u; \
    for hook in /opt/conda/etc/conda/activate.d/*.sh; do . "$hook"; done; \
    for var in QUARTO_DENO QUARTO_PANDOC QUARTO_SHARE_PATH QUARTO_CONDA_PREFIX; do \
        eval "val=\${$var:-}"; \
        [ -n "$val" ] || { echo "activation hook did not export $var"; exit 1; }; \
    done; \
    test -x "$QUARTO_DENO"; \
    test -d "$QUARTO_SHARE_PATH"; \
    quarto --version; \
    Rscript -e 'for (p in c("optparse","quarto","yaml","data.table","dplyr","DT","htmltools","ggplot2","svglite","circlize","knitr","R.utils","base64enc")) library(p, character.only = TRUE)'; \
    test "$(render_report.R --version)" = "$(cat /opt/conda/share/lrsomatic_report/VERSION)"

CMD ["render_report.R", "--help"]
